# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
palette = "catppuccin_mocha"

format = """
[î¯†](bold blue) $directory$git_branch$git_status
$username$hostname$nodejs$python$rust$golang$docker$package$battery$cmd_duration
$character
"""

# ğŸ¨ Palette Catppuccin Mocha
[palettes.catppuccin_mocha]
blue = "#89b4fa"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
purple = "#cba6f7"
cyan = "#94e2d5"
pink = "#f5c2e7"
subtext = "#a6adc8"

# ğŸ“‚ Directory
[directory]
style = "bold cyan"
truncation_length = 3
truncation_symbol = "/"
truncate_to_repo = true
read_only = " ï€£"
format = "[$path]($style)[$read_only]($style) "

# ğŸ‘¤ Username
[username]
style_user = "bold purple"
style_root = "bold blue"
format = "[$user]($style) "
show_always = true

# ğŸŒ Hostname
[hostname]
ssh_only = false
format = "on [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false

# ğŸ¦€ Rust
[rust]
format = "[via âš™ï¸ $version](red bold)"

# ğŸ›¡ï¸ Sudo
[sudo]
style = "bold green"
symbol = "ğŸ‘‘ "
disabled = false

# ğŸŒ± Git
[git_branch]
symbol = "ï˜ "
style = "bold purple"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold red"
conflicted = "ğŸ³ "
ahead = "â‡¡${count} "
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count} "
behind = "â‡£${count} "
up_to_date = "âœ“"
untracked = "ğŸ¤· "
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = "[++($count)](green) "
renamed = "ğŸ‘… "
deleted = "ğŸ—‘ "

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

# ğŸ’» Node.js
[nodejs]
symbol = "îœ˜ "
style = "bold green"
format = "[$symbol($version)]($style)"

# ğŸ Python
[python]
symbol = "îˆµ "
style = "bold yellow"
format = "[$symbol($version)]($style)"

# ğŸ¤“ Golang
[golang]
symbol = "ğŸ¹ "
style = "bold cyan"
format = "[$symbol($version)]($style)"

# ğŸ³ Docker
[docker_context]
symbol = "ïŒˆ "
style = "bold blue"
format = "[$symbol$context]($style)"

# ğŸ“¦ Package
[package]
symbol = "ï’‡ "
style = "bold pink"
format = "[$symbol$version]($style)"

# ğŸ”‹ Battery
[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ "
discharging_symbol = "ğŸ’€ "
unknown_symbol = "ï‰„ "
format = "[$symbol$percentage]($style)"

[[battery.display]]
threshold = 20
style = "bold red"

# â±ï¸ Command execution time
[cmd_duration]
min_time = 100 
format = " took [$duration]($style)"
style = "bold yellow"

# âœ Prompt symbol
[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[îŸ…](bold green)"